version: "3.3"

services:
  
  app:
    container_name: app
    build:
      context: ./predprof_teplici
      dockerfile: Dockerfile
    command:
        bash -c 'gunicorn --bind 0.0.0.0:5002 __init__:app'
    restart: always
    expose:
      - "5002"

    volumes:
      - ./data:./data


  collector:
    container_name: collector
    build:
      context: ./collect
    restart: always

    volumes:
      - ./data:./data

      
  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"


