version: "3.3"

services:
  
  app:
    container_name: app
    build:
      context: ./predprof_teplici
    command:
        'gunicorn --bind 0.0.0.0:8081 main:ssapp'
    restart: always
    expose:
      - "8081"

    volumes:
      - ./data:/app/data

  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"