version: "3.3"

services:
  
  app:
    container_name: app
    build:
      context: ./predprof_teplici
    command:
        'gunicorn --bind 0.0.0.0:5000 main:app'
    restart: always
    expose:
      - "5000"

    volumes:
      # - ./data:/app/data/
      # - ./data/main.db:/app/predprof_teplici/data/main.db
      - ./data:/data


  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"


  collector:
    container_name: collector
    build:
      context: ./collect
    restart: always

    volumes:
      - ./data:/data
