version: "3.3"

services:
  
  # app:
  #   container_name: app
  #   build:
  #     context: ./predprof_teplici
  #     dockerfile: Dockerfile
  #   command:
  #       bash -c 'gunicorn --bind 0.0.0.0:5001 main:app'
  #   restart: always
  #   expose:
  #     - "5001"

  #   volumes:
  #     # - ./data:/app/data/
  #     - ./main.db:/app/predprof_teplici/data/main.db
  #     # - ./data:/data
  #   # env_file:
  #   #     - ./.env

  testapp:
    container_name: testapp
    build:
      context: ./testapp
      dockerfile: Dockerfile
    command:
        # bash -c 'gunicorn --bind 0.0.0.0:5000 main:run_app'
        'gunicorn --bind 0.0.0.0:5000 main:run_app'
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - testapp
    ports:
      - "80:80"



  # collector:
  #   container_name: collector
  #   build:
  #     context: ./collect
  #   restart: always

  #   volumes:
  #     - ./main.db:/app/predprof_teplici/data/main.db
